// <auto-generated />
using System;
using Garage.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Garage.Migrations
{
    [DbContext(typeof(GaraOtoDbContext))]
    [Migration("20241104025311_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Garage.Data.Models.Admin", b =>
                {
                    b.Property<int>("AdminId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AdminId"));

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TenTaiKhoan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("AdminId");

                    b.ToTable("Admins");
                });

            modelBuilder.Entity("Garage.Data.Models.CSKH", b =>
                {
                    b.Property<int>("CSKHID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CSKHID"));

                    b.Property<DateTime?>("NgayChamSoc")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiDungID")
                        .HasColumnType("int");

                    b.Property<int?>("NhanVienID")
                        .HasColumnType("int");

                    b.Property<string>("NoiDungTraoDoi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("PhuongThucLienHe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("CSKHID");

                    b.HasIndex("NguoiDungID");

                    b.HasIndex("NhanVienID");

                    b.ToTable("CSKH");
                });

            modelBuilder.Entity("Garage.Data.Models.ChucVu", b =>
                {
                    b.Property<int>("ChucVuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ChucVuID"));

                    b.Property<int>("MucLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenChucVu")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("ChucVuID");

                    b.ToTable("ChucVu");
                });

            modelBuilder.Entity("Garage.Data.Models.DSDonBaoDuongXe", b =>
                {
                    b.Property<int>("DonBaoDuongID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DonBaoDuongID"));

                    b.Property<string>("MucTieuBaoDuong")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("NgayBaoDuong")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan?>("ThoiGianBaoDuong")
                        .HasColumnType("time");

                    b.Property<int?>("XeID")
                        .HasColumnType("int");

                    b.HasKey("DonBaoDuongID");

                    b.HasIndex("XeID");

                    b.ToTable("DSDonBaoDuongXe");
                });

            modelBuilder.Entity("Garage.Data.Models.DatLichBaoDuongXe", b =>
                {
                    b.Property<int>("DatLichBaoDuongID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DatLichBaoDuongID"));

                    b.Property<DateTime>("NgayDatLich")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiDungID")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("ThoiGianDatLich")
                        .HasColumnType("time");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasDefaultValue("Đang chờ xác nhận");

                    b.Property<int?>("XeID")
                        .HasColumnType("int");

                    b.HasKey("DatLichBaoDuongID");

                    b.HasIndex("NguoiDungID");

                    b.HasIndex("XeID");

                    b.ToTable("DatLichBaoDuongXe");
                });

            modelBuilder.Entity("Garage.Data.Models.DichVu", b =>
                {
                    b.Property<int>("DichVuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DichVuID"));

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("LoaiDichVuID")
                        .HasColumnType("int");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenDichVu")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("DichVuID");

                    b.ToTable("DichVu");
                });

            modelBuilder.Entity("Garage.Data.Models.GioiTinh", b =>
                {
                    b.Property<int>("GioiTinhID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GioiTinhID"));

                    b.Property<string>("TenGioiTinh")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.HasKey("GioiTinhID");

                    b.ToTable("GioiTinh");
                });

            modelBuilder.Entity("Garage.Data.Models.HoaDon", b =>
                {
                    b.Property<int>("HoaDonID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HoaDonID"));

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("LoaiGiaoDich")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("NgayGiaoDich")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NguoiDungID")
                        .HasColumnType("int");

                    b.Property<decimal>("SoTien")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("HoaDonID");

                    b.HasIndex("NguoiDungID");

                    b.ToTable("HoaDon");
                });

            modelBuilder.Entity("Garage.Data.Models.HoaDonLinhKien", b =>
                {
                    b.Property<int>("HoaDonLinhKienID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("HoaDonLinhKienID"));

                    b.Property<int?>("HoaDonID")
                        .HasColumnType("int");

                    b.Property<int?>("LinhKienID")
                        .HasColumnType("int");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.HasKey("HoaDonLinhKienID");

                    b.HasIndex("HoaDonID");

                    b.HasIndex("LinhKienID");

                    b.ToTable("HoaDonLinhKien");
                });

            modelBuilder.Entity("Garage.Data.Models.LichSuDichVu", b =>
                {
                    b.Property<int>("LichSuDichVuID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LichSuDichVuID"));

                    b.Property<int?>("DichVuID")
                        .HasColumnType("int");

                    b.Property<int?>("DonBaoDuongID")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("NgayThucHien")
                        .HasColumnType("datetime2");

                    b.Property<int?>("NhanVienID")
                        .HasColumnType("int");

                    b.HasKey("LichSuDichVuID");

                    b.HasIndex("DichVuID");

                    b.HasIndex("DonBaoDuongID");

                    b.HasIndex("NhanVienID");

                    b.ToTable("LichSuDichVu");
                });

            modelBuilder.Entity("Garage.Data.Models.LinhKien", b =>
                {
                    b.Property<int>("LinhKienID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LinhKienID"));

                    b.Property<decimal>("Gia")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MoTa")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("SoLuong")
                        .HasColumnType("int");

                    b.Property<string>("TenLinhKien")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("LinhKienID");

                    b.ToTable("LinhKien");
                });

            modelBuilder.Entity("Garage.Data.Models.NguoiDung", b =>
                {
                    b.Property<int>("NguoiDungID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NguoiDungID"));

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("GioiTinhID")
                        .HasColumnType("int");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("NguoiDungID");

                    b.HasIndex("GioiTinhID");

                    b.ToTable("NguoiDung");
                });

            modelBuilder.Entity("Garage.Data.Models.NhanVien", b =>
                {
                    b.Property<int>("NhanVienID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("NhanVienID"));

                    b.Property<int?>("ChucVuID")
                        .HasColumnType("int");

                    b.Property<string>("DiaChi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("GioiTinhID")
                        .HasColumnType("int");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("NhanVienID");

                    b.HasIndex("ChucVuID");

                    b.HasIndex("GioiTinhID");

                    b.ToTable("NhanVien");
                });

            modelBuilder.Entity("Garage.Data.Models.TheoDoiBaoDuong", b =>
                {
                    b.Property<int>("TheoDoiID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TheoDoiID"));

                    b.Property<string>("CachGiaiQuyet")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool?>("DaGiaiQuyet")
                        .HasColumnType("bit");

                    b.Property<int?>("DonBaoDuongID")
                        .HasColumnType("int");

                    b.Property<string>("VanDe")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("TheoDoiID");

                    b.HasIndex("DonBaoDuongID");

                    b.ToTable("TheoDoiBaoDuong");
                });

            modelBuilder.Entity("Garage.Data.Models.XeOTo", b =>
                {
                    b.Property<int>("XeID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("XeID"));

                    b.Property<string>("BienSoXe")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("HangXe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HinhAnh")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("MauSac")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<short?>("NamSanXuat")
                        .HasColumnType("smallint");

                    b.Property<int?>("NguoiDungID")
                        .HasColumnType("int");

                    b.HasKey("XeID");

                    b.HasIndex("NguoiDungID");

                    b.ToTable("XeOTo");
                });

            modelBuilder.Entity("Garage.Data.Models.CSKH", b =>
                {
                    b.HasOne("Garage.Data.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungID");

                    b.HasOne("Garage.Data.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("NhanVienID");

                    b.Navigation("NguoiDung");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("Garage.Data.Models.DSDonBaoDuongXe", b =>
                {
                    b.HasOne("Garage.Data.Models.XeOTo", "XeOTo")
                        .WithMany()
                        .HasForeignKey("XeID");

                    b.Navigation("XeOTo");
                });

            modelBuilder.Entity("Garage.Data.Models.DatLichBaoDuongXe", b =>
                {
                    b.HasOne("Garage.Data.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungID");

                    b.HasOne("Garage.Data.Models.XeOTo", "XeOTo")
                        .WithMany()
                        .HasForeignKey("XeID");

                    b.Navigation("NguoiDung");

                    b.Navigation("XeOTo");
                });

            modelBuilder.Entity("Garage.Data.Models.HoaDon", b =>
                {
                    b.HasOne("Garage.Data.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungID");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("Garage.Data.Models.HoaDonLinhKien", b =>
                {
                    b.HasOne("Garage.Data.Models.HoaDon", "HoaDon")
                        .WithMany()
                        .HasForeignKey("HoaDonID");

                    b.HasOne("Garage.Data.Models.LinhKien", "LinhKien")
                        .WithMany()
                        .HasForeignKey("LinhKienID");

                    b.Navigation("HoaDon");

                    b.Navigation("LinhKien");
                });

            modelBuilder.Entity("Garage.Data.Models.LichSuDichVu", b =>
                {
                    b.HasOne("Garage.Data.Models.DichVu", "DichVu")
                        .WithMany()
                        .HasForeignKey("DichVuID");

                    b.HasOne("Garage.Data.Models.DSDonBaoDuongXe", "DonBaoDuong")
                        .WithMany()
                        .HasForeignKey("DonBaoDuongID");

                    b.HasOne("Garage.Data.Models.NhanVien", "NhanVien")
                        .WithMany()
                        .HasForeignKey("NhanVienID");

                    b.Navigation("DichVu");

                    b.Navigation("DonBaoDuong");

                    b.Navigation("NhanVien");
                });

            modelBuilder.Entity("Garage.Data.Models.NguoiDung", b =>
                {
                    b.HasOne("Garage.Data.Models.GioiTinh", "GioiTinh")
                        .WithMany()
                        .HasForeignKey("GioiTinhID");

                    b.Navigation("GioiTinh");
                });

            modelBuilder.Entity("Garage.Data.Models.NhanVien", b =>
                {
                    b.HasOne("Garage.Data.Models.ChucVu", "ChucVu")
                        .WithMany()
                        .HasForeignKey("ChucVuID");

                    b.HasOne("Garage.Data.Models.GioiTinh", "GioiTinh")
                        .WithMany()
                        .HasForeignKey("GioiTinhID");

                    b.Navigation("ChucVu");

                    b.Navigation("GioiTinh");
                });

            modelBuilder.Entity("Garage.Data.Models.TheoDoiBaoDuong", b =>
                {
                    b.HasOne("Garage.Data.Models.DSDonBaoDuongXe", "DonBaoDuong")
                        .WithMany()
                        .HasForeignKey("DonBaoDuongID");

                    b.Navigation("DonBaoDuong");
                });

            modelBuilder.Entity("Garage.Data.Models.XeOTo", b =>
                {
                    b.HasOne("Garage.Data.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("NguoiDungID");

                    b.Navigation("NguoiDung");
                });
#pragma warning restore 612, 618
        }
    }
}
